apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    type: c2mon-server
  name: c2mon-server
spec:
  replicas: 1
  selector:
    matchLabels:
      type: c2mon-server
  template:
    metadata:
      labels:
        type: c2mon-server
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.31.0
          command: ['sh', '-c', 'sleep 30']
          imagePullPolicy: IfNotPresent
      containers:
      - name: c2mon-server
        ports:
          - containerPort: 11211 # REST port number.
          - containerPort: 47100 # communication SPI port number.
          - containerPort: 47500 # discovery SPI port number.
          - containerPort: 49112 # JMX port number.
          - containerPort: 10800 # SQL port number.
          - containerPort: 10900 # Thin clients port number.
        envFrom:
          - configMapRef:
              name: c2mon-server-properties
        image: cern/c2mon:experimental-cache-1.9.3-SNAPSHOT
        imagePullPolicy: Always
      serviceAccountName: ignite
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    type: c2mon-server
  name: c2mon-server
spec:
  ports:
    - name: c2mon-server
      port: 9001
      targetPort: 9001
  selector:
    type: c2mon-server